import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Lato } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import TanStackProvider from "./TanStackProvider";
import { Toaster } from "@/components/ui/toast";
import { ThemeProvider } from "@/components/theme-provider";
import ProjectContextProvider from "@/context/ProjectContext";
import TaskContextProvider from "@/context/TaskContext";


const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  variable: "--font-lato",
});

const roboto = Roboto({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Stack Forge",
  description: "Generated By Shawon Mondol Shibu",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
  lang="en"
  className={cn(
    "h-full antialiased",
    lato.variable,
    geistSans.variable,
    geistMono.variable,
    roboto.variable,
    "font-sans"
  )}

  suppressHydrationWarning={true}
>
      <body className="min-h-full flex flex-col">
        <TanStackProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster />
              <TaskContextProvider>
            <ProjectContextProvider>

              {children}
              </ProjectContextProvider>
              </TaskContextProvider>
          </ThemeProvider>
        </TanStackProvider>
      </body>
    </html>
  );
}
